version: '3.8'
services:
  packs-calculator:
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    image: repartners/golang-dev
    ports:
      - "3333:3000"
    networks:
      - repartners
    volumes:
      - ./:/go/src/repartners
    command: ["/bin/sh", "-c", "gin --buildArgs=\"-buildvcs=false\" -t packs-calculator run"]

networks:
  repartners:
    name: repartners
    driver: bridge

